import { StyleSheet, Dimensions } from 'react-native';
import COLORS from './colors';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const S = StyleSheet.create({
  mainWrapper: { flex: 1, backgroundColor: COLORS.bg },
  screen: { flex: 1, backgroundColor: COLORS.bg },
  appHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 58, paddingBottom: 16, backgroundColor: COLORS.surface, borderBottomWidth: 1 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 12 },
  headerIconBox: { width: 46, height: 46, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  headerGreeting: { fontSize: 17, fontWeight: '700', color: COLORS.text, letterSpacing: -0.3 },
  headerSubtitle: { fontSize: 12, fontWeight: '600', marginTop: 2, letterSpacing: 0.2 },
  avatarBtn: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  avatarBtnText: { fontSize: 17, fontWeight: '800' },
  backHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 58, paddingBottom: 16, backgroundColor: COLORS.surface, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  backBtn2: { width: 40, height: 40, borderRadius: 12, backgroundColor: COLORS.surfaceAlt, justifyContent: 'center', alignItems: 'center' },
  backArrow: { fontSize: 24, color: COLORS.text, lineHeight: 28 },
  backTitle: { fontSize: 17, fontWeight: '700', color: COLORS.text, flex: 1, textAlign: 'center', marginHorizontal: 8 },
  tabBar: { flexDirection: 'row', backgroundColor: COLORS.surface, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 10, gap: 3, position: 'relative' },
  tabItemActive: {},
  tabLabel: { fontSize: 11, fontWeight: '700', color: COLORS.textLight, letterSpacing: 0.2 },
  tabIndicator: { position: 'absolute', bottom: 0, left: '20%', right: '20%', height: 2.5, borderRadius: 2 },
  scrollPad: { padding: 20, paddingBottom: 100 },
  heroCard: { borderRadius: 24, padding: 24, marginBottom: 16, overflow: 'hidden' },
  heroLabel: { fontSize: 13, color: 'rgba(255,255,255,0.8)', fontWeight: '600', letterSpacing: 0.3 },
  heroAmount: { fontSize: 38, fontWeight: '900', color: '#fff', letterSpacing: -1, marginTop: 6, marginBottom: 6 },
  heroTrend: { backgroundColor: 'rgba(255,255,255,0.2)', alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  heroTrendText: { fontSize: 12, color: '#fff', fontWeight: '700' },
  auctionBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#1B3A1E', borderRadius: 18, padding: 16, marginBottom: 16 },
  auctionBannerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  auctionBannerTitle: { fontSize: 15, fontWeight: '800', color: '#fff' },
  auctionBannerSub: { fontSize: 12, color: 'rgba(255,255,255,0.7)', marginTop: 3 },
  auctionLivePill: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.15)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  auctionLiveTxt: { color: '#fff', fontSize: 12, fontWeight: '900', letterSpacing: 0.5 },
  statsGrid: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  statCard: { flex: 1, borderRadius: 16, padding: 14, alignItems: 'center' },
  statValue: { fontSize: 20, fontWeight: '900', marginBottom: 3 },
  statLabel: { fontSize: 10, color: COLORS.textLight, fontWeight: '700', textAlign: 'center', letterSpacing: 0.2 },
  signalCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 16, padding: 14, marginBottom: 16, gap: 12, borderLeftWidth: 4, borderWidth: 1, borderColor: COLORS.borderLight },
  signalDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.primaryLight },
  signalTitle: { fontSize: 13, fontWeight: '700', color: COLORS.text, marginBottom: 3 },
  signalText: { fontSize: 12, color: COLORS.textMid, lineHeight: 18 },
  featureCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 18, padding: 16, marginBottom: 20, gap: 14, borderWidth: 1, borderColor: COLORS.borderLight },
  featureCardIcon: { width: 52, height: 52, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  featureCardTitle: { fontSize: 15, fontWeight: '700', color: COLORS.text, marginBottom: 3 },
  featureCardSub: { fontSize: 12, color: COLORS.textLight },
  featureCardChevron: { fontSize: 24, fontWeight: '300' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, marginTop: 4 },
  sectionTitle: { fontSize: 17, fontWeight: '800', color: COLORS.text, letterSpacing: -0.3 },
  sectionAction: { fontSize: 13, fontWeight: '700' },
  listingRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 16, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: COLORS.borderLight },
  listingEmoji: { width: 50, height: 50, borderRadius: 14, backgroundColor: COLORS.primaryBg, justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  listingName: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  listingQty: { fontSize: 12, color: COLORS.textLight, marginTop: 3 },
  listingPrice: { fontSize: 15, fontWeight: '800' },
  listingTrend: { fontSize: 12, fontWeight: '700', marginTop: 3 },
  fab: { position: 'absolute', bottom: 28, right: 22, width: 60, height: 60, borderRadius: 30, justifyContent: 'center', alignItems: 'center', elevation: 6, shadowColor: COLORS.primaryMid, shadowOpacity: 0.35, shadowRadius: 12, shadowOffset: { width: 0, height: 4 } },
  toolsTagline: { fontSize: 13, color: COLORS.textMid, marginBottom: 20, lineHeight: 20 },
  toolsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 12 },
  toolCard: { width: (SCREEN_WIDTH - 52) / 2, backgroundColor: COLORS.surface, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: COLORS.borderLight },
  toolIconBg: { width: 56, height: 56, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  toolTitle: { fontSize: 14, fontWeight: '800', color: COLORS.text, marginBottom: 5, letterSpacing: -0.2 },
  toolDesc: { fontSize: 12, color: COLORS.textLight, lineHeight: 17 },
  wideToolCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 20, padding: 18, gap: 14, borderWidth: 1, borderColor: COLORS.borderLight },
  pillBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  pillBadgeText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.3 },
  infoBox: { backgroundColor: COLORS.primaryBg, borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: COLORS.primaryBgDark },
  infoBoxTitle: { fontSize: 14, fontWeight: '800', marginBottom: 5, color: COLORS.primaryMid },
  infoBoxText: { fontSize: 13, lineHeight: 19, color: COLORS.primaryMid },
  formCard: { backgroundColor: COLORS.surface, borderRadius: 20, padding: 20, marginBottom: 16, borderWidth: 1, borderColor: COLORS.borderLight },
  cardSectionTitle: { fontSize: 15, fontWeight: '800', color: COLORS.text, marginBottom: 14 },
  inputLabel: { fontSize: 13, fontWeight: '700', color: COLORS.textMid, marginBottom: 8, letterSpacing: 0.1 },
  input: { backgroundColor: COLORS.surfaceAlt, borderWidth: 1.5, borderColor: COLORS.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15, color: COLORS.text },
  searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, marginHorizontal: 20, marginVertical: 12, paddingHorizontal: 14, borderRadius: 16, borderWidth: 1.5, borderColor: COLORS.border, gap: 10 },
  searchInput: { flex: 1, paddingVertical: 13, fontSize: 15, color: COLORS.text },
  micPill: { backgroundColor: COLORS.primaryMid, padding: 8, borderRadius: 10 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: COLORS.surface, marginRight: 8 },
  filterChipText: { fontSize: 13, fontWeight: '700', color: COLORS.textMid },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  chip: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: COLORS.surface },
  chipActive: { borderColor: COLORS.primaryMid, backgroundColor: COLORS.primaryBg },
  chipText: { fontSize: 13, fontWeight: '700', color: COLORS.textMid },
  chipTextActive: { color: COLORS.primaryMid },
  productsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  productCard: { width: (SCREEN_WIDTH - 52) / 2, backgroundColor: COLORS.surface, borderRadius: 18, padding: 14, borderWidth: 1, borderColor: COLORS.borderLight },
  productCardEmoji: { width: '100%', height: 90, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  productCardName: { fontSize: 14, fontWeight: '800', color: COLORS.text },
  productCardPrice: { fontSize: 15, fontWeight: '900', marginTop: 3 },
  productCardMeta: { fontSize: 11, color: COLORS.textLight },
  productCardFarmer: { fontSize: 11, color: COLORS.textLight, marginTop: 3 },
  farmerCard: { flexDirection: 'row', backgroundColor: COLORS.surface, borderRadius: 20, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: COLORS.borderLight },
  farmerAvatar: { width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center' },
  farmerAvatarText: { fontSize: 16, fontWeight: '900' },
  farmerName: { fontSize: 15, fontWeight: '800', color: COLORS.text },
  farmerMeta: { fontSize: 12, color: COLORS.textLight },
  farmerPriceRange: { fontSize: 13, fontWeight: '800', color: COLORS.primaryMid },
  farmerDeliveries: { fontSize: 11, color: COLORS.textLight, marginTop: 2 },
  farmerBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  farmerBadgeText: { fontSize: 11, fontWeight: '800' },
  verifiedBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.primaryBg, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  verifiedBadgeText: { fontSize: 11, fontWeight: '800', color: COLORS.primaryMid },
  cropPill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  cropPillText: { fontSize: 11, fontWeight: '700' },
  contactBtn: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 10, borderWidth: 1.5 },
  contactBtnText: { fontSize: 12, fontWeight: '800' },
  recCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 16, padding: 16, marginBottom: 10, borderWidth: 1, borderColor: COLORS.borderLight },
  recCardName: { fontSize: 15, fontWeight: '800', color: COLORS.text, marginBottom: 3 },
  recCardDesc: { fontSize: 12, color: COLORS.textLight },
  primaryBtn: { backgroundColor: COLORS.primaryMid, paddingVertical: 16, paddingHorizontal: 24, borderRadius: 16, alignItems: 'center', marginTop: 12 },
  primaryBtnText: { color: '#fff', fontSize: 16, fontWeight: '800', letterSpacing: 0.2 },
  secondaryBtn: { flex: 1, paddingVertical: 16, borderRadius: 16, alignItems: 'center', borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: COLORS.surface },
  secondaryBtnText: { fontSize: 15, fontWeight: '800' },
  orderCard: { backgroundColor: COLORS.surface, borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: COLORS.borderLight, borderLeftWidth: 4 },
  orderCrop: { fontSize: 14, fontWeight: '800', color: COLORS.text, marginBottom: 2 },
  orderMeta: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  orderId: { fontSize: 11, color: COLORS.textLight, marginTop: 6, fontWeight: '700' },
  statusPill: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  statusPillText: { fontSize: 11, fontWeight: '800' },
  marketRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: COLORS.borderLight },
  marketCropName: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  marketCropMeta: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  marketCropAvail: { fontSize: 12, fontWeight: '700', marginTop: 3 },
  marketPrice: { fontSize: 16, fontWeight: '900', marginBottom: 8 },
  negotiateBtn: { borderWidth: 1.5, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5 },
  negotiateBtnTxt: { fontSize: 12, fontWeight: '800' },
  analyticsRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 16, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: COLORS.borderLight },
  analyticsCropName: { fontSize: 14, fontWeight: '800', color: COLORS.text },
  analyticsCropQty: { fontSize: 12, color: COLORS.textLight },
  analyticsCropSpend: { fontSize: 14, fontWeight: '800' },
  progressBg: { height: 5, backgroundColor: COLORS.borderLight, borderRadius: 3 },
  progressFill: { height: 5, borderRadius: 3 },
  photoUpload: { backgroundColor: COLORS.surface, borderWidth: 2, borderColor: COLORS.borderLight, borderStyle: 'dashed', borderRadius: 20, height: 160, justifyContent: 'center', alignItems: 'center', marginBottom: 16, overflow: 'hidden' },
  photoIconBox: { width: 64, height: 64, borderRadius: 18, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  photoUploadText: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  photoUploadSub: { fontSize: 12, color: COLORS.textLight, marginTop: 4 },
  storeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  storeCard: { width: (SCREEN_WIDTH - 52) / 2, backgroundColor: COLORS.surface, borderRadius: 18, padding: 14, borderWidth: 1, borderColor: COLORS.borderLight },
  storeEmojiBox: { width: 52, height: 52, borderRadius: 14, backgroundColor: COLORS.primaryBg, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  storeCatLabel: { fontSize: 10, fontWeight: '800', color: COLORS.primaryMid, textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 4 },
  storeItemName: { fontSize: 13, fontWeight: '700', color: COLORS.text, marginBottom: 2, lineHeight: 18 },
  storeUnit: { fontSize: 11, color: COLORS.textLight, marginBottom: 8 },
  storePrice: { fontSize: 15, fontWeight: '900', marginBottom: 10 },
  addCartBtn: { backgroundColor: COLORS.primaryMid, paddingVertical: 8, borderRadius: 10, alignItems: 'center' },
  addCartBtnText: { color: '#fff', fontWeight: '800', fontSize: 12 },
  cartBadge: { position: 'absolute', top: -4, right: -4, backgroundColor: COLORS.danger, borderRadius: 8, width: 16, height: 16, justifyContent: 'center', alignItems: 'center' },
  cartBadgeText: { color: '#fff', fontSize: 10, fontWeight: '800' },
  newsCard: { borderRadius: 18, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: COLORS.borderLight },
  newsTagPill: { backgroundColor: 'rgba(0,0,0,0.07)', paddingHorizontal: 9, paddingVertical: 3, borderRadius: 8 },
  newsTagText: { fontSize: 11, fontWeight: '800', color: COLORS.textMid },
  newsTime: { fontSize: 11, color: COLORS.textLight },
  newsTitle: { fontSize: 14, fontWeight: '700', color: COLORS.text, lineHeight: 21, marginBottom: 8 },
  newsReadMore: { fontSize: 12, fontWeight: '800' },
  livePriceCard: { backgroundColor: COLORS.surface, borderRadius: 18, padding: 16, marginBottom: 16, borderWidth: 1.5, borderColor: COLORS.primaryLight, flexDirection: 'row', alignItems: 'center' },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.primaryLight, marginRight: 6 },
  livePriceLabel: { fontSize: 12, color: COLORS.primaryMid, fontWeight: '700' },
  livePriceValue: { fontSize: 28, fontWeight: '900', color: COLORS.text, marginTop: 4 },
  livePriceRange: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  refreshBtn: { padding: 8 },
  priceStatCard: { flex: 1, backgroundColor: COLORS.surface, borderRadius: 14, padding: 10, alignItems: 'center', borderWidth: 1, borderColor: COLORS.borderLight },
  priceStatLabel: { fontSize: 9, color: COLORS.textLight, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.3, marginBottom: 4 },
  priceStatValue: { fontSize: 15, fontWeight: '900', color: COLORS.text },
  priceStatChange: { fontSize: 11, fontWeight: '800', marginTop: 2 },
  chartCard: { backgroundColor: COLORS.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: COLORS.borderLight, marginBottom: 16, alignItems: 'center' },
  chartTitle: { fontSize: 13, fontWeight: '700', color: COLORS.text, marginBottom: 12, alignSelf: 'flex-start' },
  aiResultCard: { backgroundColor: COLORS.surface, borderRadius: 20, borderWidth: 2, overflow: 'hidden', marginBottom: 20 },
  aiAction: { fontSize: 20, fontWeight: '900', letterSpacing: 0.5, marginTop: 2 },
  aiReason: { fontSize: 14, color: COLORS.text, lineHeight: 22, padding: 16 },
  aiFooter: { paddingHorizontal: 16, paddingVertical: 10 },
  breakdownRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10 },
  breakdownLabel: { fontSize: 14, color: COLORS.textMid },
  breakdownValue: { fontSize: 15, fontWeight: '800' },
  profitSummary: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 14, borderRadius: 14, marginTop: 10 },
  profitSummaryLabel: { fontSize: 16, fontWeight: '800', color: COLORS.text },
  profitSummaryValue: { fontSize: 22, fontWeight: '900' },
  detailHero: { borderRadius: 24, height: 180, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  detailName: { fontSize: 24, fontWeight: '900', color: COLORS.text, letterSpacing: -0.5 },
  detailPrice: { fontSize: 22, fontWeight: '900', marginVertical: 8 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 11, borderBottomColor: COLORS.borderLight },
  detailRowLabel: { fontSize: 14, color: COLORS.textMid },
  detailRowValue: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  chatBox: { backgroundColor: COLORS.surfaceAlt, borderRadius: 16, padding: 14, marginBottom: 16, borderWidth: 1, borderColor: COLORS.borderLight },
  chatBubbleOther: { backgroundColor: COLORS.surface, padding: 12, borderRadius: 14, borderTopLeftRadius: 4, marginBottom: 8, alignSelf: 'flex-start', maxWidth: '80%', borderWidth: 1, borderColor: COLORS.borderLight },
  chatBubbleOtherText: { color: COLORS.text, fontSize: 13, lineHeight: 19 },
  chatBubbleSelf: { backgroundColor: COLORS.primaryBg, padding: 12, borderRadius: 14, borderTopRightRadius: 4, marginBottom: 8, alignSelf: 'flex-end', maxWidth: '80%' },
  chatBubbleSelfText: { color: COLORS.primaryMid, fontSize: 13, lineHeight: 19 },
  trackStep: { flexDirection: 'row', alignItems: 'center' },
  trackDot: { width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  trackTitle: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  trackTime: { fontSize: 12, color: COLORS.textLight, marginTop: 3 },
  trackLine: { width: 2, height: 28, backgroundColor: COLORS.primaryMid, marginLeft: 15, marginVertical: 4 },
  profileHero: { borderRadius: 24, padding: 28, alignItems: 'center', marginBottom: 16 },
  profileAvatar: { width: 84, height: 84, borderRadius: 42, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  profileAvatarText: { fontSize: 36, fontWeight: '900', color: '#fff' },
  profileName: { fontSize: 22, fontWeight: '900', color: COLORS.text, letterSpacing: -0.5 },
  profilePhone: { fontSize: 14, fontWeight: '600', marginTop: 4 },
});

export default S;
